apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/runtime: js
    app.openshift.io/vcs-ref: 30aa41303383c45804478df524ff8eeea2f7b8e1
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/Team4-Chat-Room-Backend
  labels:
    app: chatroom-backend
    app.kubernetes.io/instance: chatroom-backend
    app.kubernetes.io/name: chatroom-backend
  name: chatroom-backend
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: ws
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: chatroom-backend
    app.kubernetes.io/instance: chatroom-backend
    app.kubernetes.io/name: chatroom-backend
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/runtime: js
    app.openshift.io/vcs-ref: 30aa41303383c45804478df524ff8eeea2f7b8e1
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/Team4-Chat-Room-Backend
  labels:
    app: chatroom-backend
    app.kubernetes.io/instance: chatroom-backend
    app.kubernetes.io/name: chatroom-backend
  name: chatroom-backend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: chatroom-backend
      app.kubernetes.io/instance: chatroom-backend
      app.kubernetes.io/name: chatroom-backend
  template:
    metadata:
      annotations:
        app.openshift.io/runtime: js
        app.openshift.io/vcs-ref: 30aa41303383c45804478df524ff8eeea2f7b8e1
        app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/Team4-Chat-Room-Backend
      labels:
        app: chatroom-backend
        app.kubernetes.io/instance: chatroom-backend
        app.kubernetes.io/name: chatroom-backend
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/fabrizio_pietrucci/team4-chatroom-backend:30aa41303383c45804478df524ff8eeea2f7b8e1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: chatroom-backend
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/runtime: js
    app.openshift.io/vcs-ref: 30aa41303383c45804478df524ff8eeea2f7b8e1
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/Team4-Chat-Room-Backend
  labels:
    app: chatroom-backend
    app.kubernetes.io/instance: chatroom-backend
    app.kubernetes.io/name: chatroom-backend
  name: chatroom-backend
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: chatroom-backend
    weight: 100
  wildcardPolicy: None
