apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/runtime: js
    app.openshift.io/vcs-ref: e4eca253925d75b934bc5de92f38f51d6a32cf04
    app.openshift.io/vcs-uri: https://github.com/berringo/berry-wanmeng-app
  labels:
    app: nextjs-app
    app.kubernetes.io/instance: nextjs-app
    app.kubernetes.io/name: nextjs-app
  name: nextjs-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: nextjs-app
    app.kubernetes.io/instance: nextjs-app
    app.kubernetes.io/name: nextjs-app
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/runtime: js
    app.openshift.io/vcs-ref: e4eca253925d75b934bc5de92f38f51d6a32cf04
    app.openshift.io/vcs-uri: https://github.com/berringo/berry-wanmeng-app
  labels:
    app: nextjs-app
    app.kubernetes.io/instance: nextjs-app
    app.kubernetes.io/name: nextjs-app
  name: nextjs-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nextjs-app
      app.kubernetes.io/instance: nextjs-app
      app.kubernetes.io/name: nextjs-app
  template:
    metadata:
      annotations:
        app.openshift.io/runtime: js
        app.openshift.io/vcs-ref: e4eca253925d75b934bc5de92f38f51d6a32cf04
        app.openshift.io/vcs-uri: https://github.com/berringo/berry-wanmeng-app
      labels:
        app: nextjs-app
        app.kubernetes.io/instance: nextjs-app
        app.kubernetes.io/name: nextjs-app
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/berringo/berry-wanmeng-app:e4eca253925d75b934bc5de92f38f51d6a32cf04
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: berry-wanmeng-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/runtime: js
    app.openshift.io/vcs-ref: e4eca253925d75b934bc5de92f38f51d6a32cf04
    app.openshift.io/vcs-uri: https://github.com/berringo/berry-wanmeng-app
  labels:
    app: nextjs-app
    app.kubernetes.io/instance: nextjs-app
    app.kubernetes.io/name: nextjs-app
  name: nextjs-app
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: nextjs-app
    weight: 100
  wildcardPolicy: None
