apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/runtime: js
    app.openshift.io/vcs-ref: efd67963ca31298471909c2a49490cc8855db4f9
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/squad2-basp-project-client.git
  labels:
    app: basp-client-app
    app.kubernetes.io/instance: basp-client-app
    app.kubernetes.io/name: basp-client-app
  name: basp-client
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: basp-client-app
    app.kubernetes.io/instance: basp-client-app
    app.kubernetes.io/name: basp-client-app
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/runtime: js
    app.openshift.io/vcs-ref: efd67963ca31298471909c2a49490cc8855db4f9
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/squad2-basp-project-client.git
  labels:
    app: basp-client-app
    app.kubernetes.io/instance: basp-client-app
    app.kubernetes.io/name: basp-client-app
  name: basp-client
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: basp-client-app
      app.kubernetes.io/instance: basp-client-app
      app.kubernetes.io/name: basp-client-app
  template:
    metadata:
      annotations:
        app.openshift.io/runtime: js
        app.openshift.io/vcs-ref: efd67963ca31298471909c2a49490cc8855db4f9
        app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/squad2-basp-project-client.git
      labels:
        app: basp-client-app
        app.kubernetes.io/instance: basp-client-app
        app.kubernetes.io/name: basp-client-app
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/giusan_ibm/basp-client:efd67963ca31298471909c2a49490cc8855db4f9
        imagePullPolicy: IfNotPresent
        name: express-buildah-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/runtime: js
    app.openshift.io/vcs-ref: efd67963ca31298471909c2a49490cc8855db4f9
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/squad2-basp-project-client.git
  labels:
    app: basp-client-app
    app.kubernetes.io/instance: basp-client-app
    app.kubernetes.io/name: basp-client-app
  name: basp-client
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: basp-client
    weight: 100
  wildcardPolicy: None
